[ClassVersion("1.0.0.0"), FriendlyName("cDFSRepGroupConnection")]
class BMD_cDFSRepGroupConnection : OMI_BaseResource
{
    [Key, Description("The name of the DFS Replication Group.")] String GroupName;
    [Key, Description("The DFS Replication Group connection source computer name.")] String SourceComputerName;
    [Key, Description("The DFS Replication Group connection destination computer name.")] String DestinationComputerName;
    [Required, Description("Specifies whether the DSF Replication Group connection should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("A description for the DFS Replication Group connection.")] String Description;
    [Write, Description("Disable the Replication Group connection.")] Boolean DisableConnection;
    [Write, Description("Disable remote differential compression on the Replication Group connection.")] Boolean DisableRDC;
    [Write, Description("The name of the AD Domain the DFS Replication Group connection should be in.")] String DomainName;
};
