[ClassVersion("1.0.0.0"), FriendlyName("DFSReplicationGroupMembership")]
class DSC_DFSReplicationGroupMembership : OMI_BaseResource
{
    [Key, Description("The name of the DFS Replication Group.")] String GroupName;
    [Key, Description("The name of the DFS Replication Group Folder.")] String FolderName;
    [Key, Description("The computer name of the Replication Group member. This can be specified using either the ComputerName or FQDN name for the member. If an FQDN name is used and the DomainName parameter is set, the FQDN domain name must match.")] String ComputerName;
    [Write, Description("Ensures that membership is either Enabled or Disabled."),ValueMap{"Enabled","Disabled"}, Values{"Enabled","Disabled"}] String EnsureEnabled;
    [Write, Description("The local content path for the DFS Replication Group Folder.")] String ContentPath;
    [Write, Description("The local staging path for the DFS Replication Group Folder.")] String StagingPath;
    [Write, Description("The staging path quota size in MB for the DFS Replication Group Folder.")] UInt32 StagingPathQuotaInMB;
    [Write, Description("The minimum file size that DFS Replication stages during outbound replication."), ValueMap{"Size256KB","Size512KB","Size1MB","Size2MB","Size4MB","Size8MB","Size16MB","Size32MB","Size64MB","Size128MB","Size256MB","Size512MB","Size1GB","Size2GB","Size4GB","Size8GB","Size16GB","Size32GB","Size64GB","Size128GB","Size256GB","Size512GB","Size1TB","Size2TB","Size4TB","Size8TB","Size16TB","Size32TB","Size64TB","Size128TB","Size256TB","Size512TB"}, Values{"Size256KB","Size512KB","Size1MB","Size2MB","Size4MB","Size8MB","Size16MB","Size32MB","Size64MB","Size128MB","Size256MB","Size512MB","Size1GB","Size2GB","Size4GB","Size8GB","Size16GB","Size32GB","Size64GB","Size128GB","Size256GB","Size512GB","Size1TB","Size2TB","Size4TB","Size8TB","Size16TB","Size32TB","Size64TB","Size128TB","Size256TB","Size512TB"}] String MinimumFileStagingSize;
    [Read, Description("The local content and deleted path for the DFS Replication Group Folder.")] String ConflictAndDeletedPath;
    [Write, Description("The local conflict and deleted path quota size in MB.")] UInt32 ConflictAndDeletedQuotaInMB;
    [Write, Description("Specify if this content path should be read only.")] Boolean ReadOnly;
    [Write, Description("Specify if a member computer deletes files and folders immediately following inbound replication.")] Boolean RemoveDeletedFiles;
    [Write, Description("Used to configure this as the Primary Member. Every folder must have at least one primary member for initial replication to take place. Only set during initial creation of membership.")] Boolean PrimaryMember;
    [Write, Description("Specify the DFS Namespace folder path of the membership. This value does not affect replication.")] String DfsnPath;
    [Write, Description("The name of the AD Domain the DFS Replication Group this replication group is in.")] String DomainName;
};
